version: 0.2
phases:
  install:
    commands:
    - uname -a
    - yum update -y
    - dnf -y install java-21-amazon-corretto
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn install
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn package
artifacts:
  files:
    - target/naming-server-0.0.1-SNAPSHOT.jar
